### ISSUE TITLE
[question] What about `SelectMany`?

### ISSUE THREAD

**Issue by igor-lukashenya** [ffernandolima/ef-core-data-access#14]
Hi, I want to ask about `SelectMany`?

Are there any alternative or implementation for `SelectMany`?

**Comment by ffernandolima** [comment]
Hi!

For complex query operators like `SelectMany` a custom repository should be used instead.

There's an example [here](https://github.com/ffernandolima/ef-core-data-access/blob/ef-core-6/samples/EntityFrameworkCore.Data/Repositories/CustomBlogRepository.cs#L13) demonstrating how to create a custom repository and use all available features from `DbSet` and/or `IQueryable`.

The custom repository can be instantiated through `IUnitOfWork` which inherits from `IRepositoryFactory`, by accessing `CustomRepository` available method. 

Example:

``` C#
// Example: Custom Repository
var repository = _unitOfWork.CustomRepository<ICustomBlogRepository>();

var urls = await repository.GetAllBlogUrlsAsync()
      .ConfigureAwait(continueOnCapturedContext: false);
```

Also, the `SelectMany` official documentation can be found out [here](https://docs.microsoft.com/en-us/ef/core/querying/complex-query-operators#selectmany).
