### ISSUE TITLE
[Feature Request] ```Task<T> UpdateAsync()``` method

### ISSUE THREAD

**Issue by nausixkiz** [ffernandolima/ef-core-data-access#16]
Example:
```
...
public void UpdateBlog()
{
    var repository = _unitOfWork.Repository<Blog>();

    var blog = await repository.UpdateAsync(model); ///Not work
    
    _unitOfWork.SaveChangesAsync();
}
...
```

Look like ```IAsyncRepository<T>``` in ```EntityFrameworkCore.Repository.Interfaces``` doesn't have method below:
```
 Task<T> UpdateAsync(
      T entity, 
      params Expression<Func<T, object>>[] properties
      CancellationToken cancellationToken = default (CancellationToken));
```

**Comment by ffernandolima** [comment]
Hi!

There isn't this method because EF Core doesn't support it.

Please see this [issue](https://github.com/dotnet/efcore/issues/18746) for more info.

**Comment by nausixkiz** [comment]
Thank @ffernandolima,
Does this mean we have to remove the old record and add a new one when we want using async?

**Comment by ffernandolima** [comment]
@nausixkiz you can simply use the sync method. It'd be fine.
