### ISSUE TITLE
Support for ExecutionStrategy (in conjunction with Transactions)

### ISSUE THREAD

**Issue by KennethScott** [ffernandolima/ef-core-data-access#20]
Have you ever considered adding support for [ExecutionStrategy](https://learn.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.executionstrategyextensions.executeintransaction?view=efcore-7.0) in conjunction with transactions?  I recently ran across a situation where I wasn't able to use the normal create Transaction because of conflicts with the application's existing retry strategy.  After a lot of trial and error, I finally settled on creating a new execution strategy and executing the transaction off it.  They have an extension method available that wraps the try/catch begin/commit/rollback so there wasn't much to a barebones version (although there are several more signatures you could support) - this was my down and dirty (**and definitely not fully tested**) method on the UnitOfWork:

````csharp
public async Task ExecuteInTransactionAsync(Func<Task> operation, Func<Task<bool>> verifySucceeded = null)
{
    var strategy = _context.Database.CreateExecutionStrategy();

    await strategy.ExecuteInTransactionAsync(
        async () => await operation(),
        () => verifySucceeded != null ? verifySucceeded() : Task.FromResult(true)
    );
}
````

and then you just call it as needed like:
````csharp
await _unitOfWork.ExecuteInTransactionAsync(
  async () =>
  {
       ......
       await whatever.SaveChangesAsync();
       await whatever.SaveChangesAsync();
       await whatever.SaveChangesAsync();
       ....
  });
````

Just thought I'd mention it while it was on my mind.

Thanks-

**Comment by ffernandolima** [comment]
Hi @KennethScott!

I apologize for the delayed response.

Currently, it's possible to create and use an execution strategy by accessing the `DbContext` property from the `UnitOfWork`:

`var strategy = _unitOfWork.DbContext.Database.CreateExecutionStrategy();`

As you mentioned, there are many overloads for the `ExecuteInTransaction` and `ExecuteInTransactionAsync` methods. Therefore, directly wrapping all of them within the `UnitOfWork` doesn't seem to be worthwhile.

I believe that wrapping only the `CreateExecutionStrategy` method within the `UnitOfWork` could be beneficial and also save some effort. By doing so, developers would be able to choose the best `ExecuteInTransaction` or `ExecuteInTransactionAsync` method that suits their requirements.

By the way, thank you for the suggestion.

**Comment by ffernandolima** [comment]
Closing the issue for now.
