### ISSUE TITLE
How do used UpdateAsync

### ISSUE THREAD

**Issue by MohMehrnia** [ffernandolima/ef-core-data-access#25]
How do used UpdateAsync for updateing all property?

**Comment by ffernandolima** [comment]
Hi @MohMehrnia!

If you're talking about [this](https://github.com/ffernandolima/ef-core-data-access/blob/e243bb3472de8df78c58d1228a2a24474531585a/src/EntityFrameworkCore.Repository/Repository.cs#L885) UpdateAsync method, it uses the EF Core ExecuteUpdateAsync internally to execute batch updates.

You need to specify manually the properties you want to update.

Check these StackOverflow questions, they may help you:

- [EF Core 7: How To Use ExecuteUpdateAsync Without Manually Specifying Fields and Values](https://stackoverflow.com/questions/76693742/ef-core-7-how-to-use-executeupdateasync-without-manually-specifying-fields-and)

- [How to conditionally SetProperty with Entity Framework Core ExecuteUpdate?](https://stackoverflow.com/questions/75924095/how-to-conditionally-setproperty-with-entity-framework-core-executeupdate)

I hope I've helped you.

**Comment by ffernandolima** [comment]
Closing this issue for now. In case you need further assistance, please let me know.
