### ISSUE TITLE
error when update

### ISSUE THREAD

**Issue by MohMehrnia** [ffernandolima/ef-core-data-access#26]
when update entity show me below error

`The database operation was expected to affect 1 row(s), but actually affected 0 row(s)`

update code is 

var updatedCourse = _mapper.Map<Model.Course.Course>(request.Course);
 var course = repository.Update(updatedCourse);
await unitOfWork.SaveChangesAsync(cancellationToken: cancellationToken);

**Comment by ffernandolima** [comment]
Hi @MohMehrnia!

Can you please provide me a simple app with the minimum code structure with some repro steps? By doing that, I'd be able to help you.

Btw, it seems to be something from the EF Core and not from the library.

Thank you.

**Comment by MohMehrnia** [comment]
[https://mega.nz/file/S5ZBwTBR#fmBPubkKZEuzI_vaUaVBmyX-29oir7zdAJnM58YQoaU](Full Source Code)

**Comment by ffernandolima** [comment]
Hi @MohMehrnia! I hope you're doing well.
I couldn't build the project you provided me. It seems like it misses 2 reference projects.
Please provide me a simple app with some repro steps, so that I can help you.
Thanks for understanding.

**Comment by ffernandolima** [comment]
Due to the inactivity of this issue, I am closing it for now.
